version: '3.9'

services:

  user-service:
    build: ./user-service
    ports:
      - "8001:8000"

  room-service:
    build: ./room-service
    ports:
      - "8002:8000"

  reservation-service:
    build: ./reservation-service
    ports:
      - "8003:8000"